INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (3, 'X RPL 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (4, 'X RPL 2', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (5, 'X MKT 1', 4);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (6, 'X MKT 2', 4);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (9, 'XI-RPL', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (10, 'XI-TKJ 2', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (13, 'X TKJ 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (14, 'X MM 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (15, 'XI-TKJ 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (16, 'XI-MM 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (3, 'X RPL 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (4, 'X RPL 2', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (5, 'X MKT 1', 4);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (6, 'X MKT 2', 4);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (9, 'XI-RPL', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (10, 'XI-TKJ 2', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (13, 'X TKJ 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (14, 'X MM 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (15, 'XI-TKJ 1', 1);
INSERT INTO `tb_kelas` (`id_kelas`, `kelas`, `id_prodi`) VALUES (16, 'XI-MM 1', 1);
