INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (1, 'Networking', 1, NULL, '2024-05-10 07:57:51');
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (2, 'Editing', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (3, 'Programming', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (4, 'Khusus', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (5, 'Budaya Idustri', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (6, 'Info PPDB', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (7, 'Mars SMKN 1 Purwosari', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (8, 'Metaverse', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (9, 'Informasi', 3, NULL, '2024-05-10 08:12:01');
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (10, 'Prestasi', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (11, 'Peristiwa', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (12, 'PPDB', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (13, 'MPLS', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (29, 'Lowongan Pekerjaan', 2, '2024-06-13 10:45:00', '2024-06-13 10:45:00');
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (30, 'Sekolah', 2, '2024-06-13 11:05:25', '2024-06-13 11:12:48');
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (1, 'Networking', 1, NULL, '2024-05-10 07:57:51');
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (2, 'Editing', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (3, 'Programming', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (4, 'Khusus', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (5, 'Budaya Idustri', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (6, 'Info PPDB', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (7, 'Mars SMKN 1 Purwosari', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (8, 'Metaverse', 1, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (9, 'Informasi', 3, NULL, '2024-05-10 08:12:01');
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (10, 'Prestasi', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (11, 'Peristiwa', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (12, 'PPDB', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (13, 'MPLS', 3, NULL, NULL);
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (29, 'Lowongan Pekerjaan', 2, '2024-06-13 10:45:00', '2024-06-13 10:45:00');
INSERT INTO `tb_pemberitahuan_category` (`id_pemberitahuan_category`, `pemberitahuan_category_name`, `type`, `created_at`, `updated_at`) VALUES (30, 'Sekolah', 2, '2024-06-13 11:05:25', '2024-06-13 11:12:48');
